listening-port=3478
tls-listening-port=5349
listening-ip=192.168.10.10
realm=your_server.ru
use-auth-secret
static-auth-secret=UU1c6vpOcgAvzxnCCFvTox2vJAnWQYfI
relay-ip=192.168.10.10
min-port=20000
max-port=20500
cert=/etc/letsencrypt/live/npm-11/fullchain.pem
pkey=/etc/letsencrypt/live/npm-11/privkey.pem
fingerprint
verbose

log-file=stdout
no-stdout-log

allocation-default-address-lifetime=7200
max-allocate-lifetime=7200
stale-nonce-timeout=86400
stale-session-timeout=1200
mobility
